# 第四章：Python 物件
## List : 串列 [ ]
## Tuple : 不能更新的串列 ( )
## Dict: 有鍵值(key)的串列 { }

## List 串列

In [ ]:
my_list0=[] #[]中的內容
my_list1 = list()
my_list2 = ['python', 'js', 'SQL'] #顯示[]中內容
print(my_list0) 
print(my_list1)
print(my_list2)
print(my_list2[0]) #顯示python
print(my_list2[1]) #顯示js
print(my_list2[2]) #顯示SQL

[]
[]
['python', 'js', 'SQL']
python
js
SQL


## 附加於最後

In [ ]:
my_list2 = ['python', 'js', 'SQL'] 
my_list2.append('java')
print(my_list2[3])
#長度len()
print(len(my_list2)) #第二是java
print(len(my_list2[0]))

java
4
6


## 新增至特定位置

In [ ]:
my_list3 = ['python', 'js', 'SQL']
my_list3.insert(0, 'java')
print(my_list3) #顯示java python js SQL

['java', 'python', 'js', 'SQL']


## 刪除

In [ ]:
my_list4 = ['java', 'python', 'js', 'SQL']
del my_list4[0]
print(my_list4) #從0-3 顯示 python js SQL
del my_list4[-1]
print(my_list4) #扣1 顯示Python js

['python', 'js', 'SQL']
['python', 'js']


## 檢查是否存在

In [ ]:
my_list4 = ['java', 'python', 'js', 'SQL']
print('java' in my_list4) #檢查是否存在 true
print('go' in my_list4) #檢查是否存在 flase

True
False


## 串列重複

In [ ]:
a=[1,2] 
print(a*5) #1,2重複5次

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]


## 串列取值

In [ ]:
a=[1,2,3,4,5,6,7,8,9]
b=a[0:3] #範圍取值
print(b)
c=a[0:9:2] #間隔取值
print(c)
del a[7:9] #刪除串列某範圍的值
print(a)
print(min(a)) #串列最小值
print(max(a))  #串列最大值
print(a.index(1)) #1出現的索引位置
print(a.count(1)) #1出現的次數
a.reverse()  #串列反轉
print(a)
a.sort()     #串列排序
print(a)

[1, 2, 3]
[1, 3, 5, 7, 9]
[1, 2, 3, 4, 5, 6, 7]
1
7
0
1
[7, 6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6, 7]


# Chap.4 numpy套件(numeric python)
## 為什麼需要numpy?
* numpy由c撰寫，速度快python 10~1000倍以上
* numpy儲存結果較正確，python數字儲存不正確
* numpy節省記憶體儲存空間
* numpy的向量(矩陣計算)速度快
* numpy的取值方便

In [4]:
a_list=[1,2,3,4,5]
print(a_list*3) #重複3次

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [5]:
#numpy套件的ndarray型態,提供element-wise的操作
import numpy as np
a=np.array([1,2,3,4,5])
print(a*3)

[ 3  6  9 12 15]


In [6]:
a=np.array([1,2,3,4,5])
print(type(a))
print(a.shape) #ndaary的形狀
print(a.dtype) #資料的型態
print(a.ndim) #維度

<class 'numpy.ndarray'>
(5,)
int64
1


In [3]:
import numpy as np
z=np.zeros(6)
print(z)
z=np.zeros((2,3,4))
print(z)
print(np.arange(10))

[0. 0. 0. 0. 0. 0.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[0 1 2 3 4 5 6 7 8 9]


## ndarray的進階操作

In [7]:
my_array=np.arange(10) #除了10 從0開始
print(my_array)
print(my_array[0])
print(my_array[0:5]) #除了5 從0開始

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


### 2維資料取值

In [8]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:]) #取第一維的資料
print(my_2d_array[:,1]) #取所有維度中，第一位置的資料
print(my_2d_array[1,1]) #顯示2維資料的取值，都是從0開始

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [9]:
my_array=np.arange(0,10) #除了10以外 從0開始
print(my_array) #結果是10結果是10
print(my_array.shape)
my_2d_array=my_array.reshape(2,5)
print(my_2d_array)
print((np.arange(0,100).reshape(10,10))) #10行10列

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
