#涵式
- 獨立一組程式碼
- 通常可以有0-多個參數, 0-1個輸出
- 涵式輸入參數可以有預設值

In [ ]:
#傳統的程式寫法
import math
radius=int(input("請輸入圓的半徑:"))
area=radius * radius * math.pi
print("圓的面積為:",area)

請輸入圓的半徑:5
圓的面積為: 78.53981633974483


In [ ]:
import math
def circle_area(radius):
   area=radius * radius * math.pi
   return area
print(circle_area(10))
print(circle_area(5))

314.1592653589793
78.53981633974483


# numpy套件

In [ ]:
a_list=[1,2,3,4,5]
print(a_list*3) #a_list的內容*3次

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
#numpy套件ndarray型態，提供element-wise的操作
import numpy as np
a_ndarray=np.array([1,2,3,4,5])
print(a_ndarray*3) #a_ndarray3次方 顯示 3 6 9 12 15 

[ 3  6  9 12 15]


In [ ]:
print(type(a_ndarray))
print(a_ndarray.ndim) #ndarray的維度
print(a_ndarray.shape) #ndarray的shape
print(a_ndarray.dtype) #ndarray的資料型態

<class 'numpy.ndarray'>
1
(5,)
int64


In [ ]:
z=np.zeros(6)
print(z)  #六個元素都為0的1d ndarray
print(np.zeros((2,6)))  #12個元素都為0的2d ndarray
print(np.empty((2,6,2))) #24個元素都未初始化的值
print(np.arange(10)) # 10個元素為0-9的1d ndarray

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[2.59496874e-316 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]]
[0 1 2 3 4 5 6 7 8 9]


# ndarray的進階操作

In [ ]:
my_array=np.arange(10) #不包含10 從0開始
print(my_array)
print(my_array[0])
print(my_array[0:5]) #不包含5 從0開始

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [ ]:
#2維ndarray取值
my_2d_array = np.array([np.arange(0,5), np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:]) #第二列資料
print(my_2d_array[:,1]) #第二欄資料
print(my_2d_array[1,1]) #第二列第二欄的資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [ ]:
#假設有六個組別"Modern Web", "DevOps", "Cloud", 
#"Big Data", "Security", "自我挑戰組"
#其參加人數分別為56, 8, 19, 14, 6, 71人
groups=["Modern Web", "DevOps",  "Cloud","Big Data", "Security", "自我挑戰組"] #顯示Modern Web", "DevOps",  "Cloud","Big Data", "Security", "自我挑戰組
ironman = [56,8,19,14,6,71] #顯示參加人數[56  8 19 14  6 71]
groups_array=np.array(groups)
ironman_array=np.array(ironman)
print(groups_array)
print(ironman_array)

['Modern Web' 'DevOps' 'Cloud' 'Big Data' 'Security' '自我挑戰組']
[56  8 19 14  6 71]


In [ ]:
#用人數去篩選組別
print(ironman_array >= 10)
print(groups_array[ironman_array >= 10])
print(groups_array != "自我挑戰組")
print(ironman_array[groups_array != "自我挑戰組"])

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']
[ True  True  True  True  True False]
[56  8 19 14  6]


# Ndarray轉置

In [ ]:
my_1d_array=np.arange(10) #不包含10 從0開始
print(my_1d_array)
my_2d_array=my_1d_array.reshape((2,5))
print(my_2d_array)
print(my_2d_array.T)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [ ]:
print(np.arange(24).reshape(4,6)) #4列 一列6個數字 不包含24 從0開始

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
#ndarray nan(空值)
nan_array=np.array([56,8,19,14,6, np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]
